package:
  name:    {{ name }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"


build:
  number: 0
  noarch: python
  entry_points:
    - selenoprofiles = selenoprofiles4.selenoprofiles4:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - python >=3.6,<3.10
    - requests >=2.27
    - bioconda::blast-legacy
    - bioconda::wise2
    - bioconda::exonerate
    - bioconda::mafft
    - bioconda::biopython
    - biobuilds::obonet
    - gawk
    - networkx
    - requests
    

test:
  imports:
    - {{ name }}

  commands:
    - selenoprofiles -h

about:
  home: "https://github.com/marco-mariotti/{{name}}"
  license: MIT
  license_family: MIT
  license_file: 
  summary: ""https://github.com/marco-mariotti/selenoprofiles4
  doc_url: "https://github.com/marco-mariotti/{{name}}"
  dev_url: 

extra:
  recipe-maintainers:
    - marco-mariotti
