{% set name = "selenoprofiles4" %}
{% set version = environ.get("PKG_VERSION") %}

package:
  name:    {{ name }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"


build:
  number: 0
  noarch: python
  entry_points:
    - selenoprofiles = selenoprofiles4.selenoprofiles4:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.12, <3.13
  run:
    - python >=3.12, <3.13
    - requests 
    - bioconda::blast-legacy
    - bioconda::wise2
    - bioconda::exonerate
    - bioconda::mafft
    - biopython
    - obonet
    - gawk
    - networkx 
    - easyterm >=1.0.0

test:
  imports:
    - {{ name }}

  commands:
    - selenoprofiles -h

about:
  home: "https://github.com/marco-mariotti/{{name}}"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "https://github.com/marco-mariotti/{{name}}"
  doc_url: "https://github.com/marco-mariotti/{{name}}"
  dev_url: 

extra:
  recipe-maintainers:
    - marco-mariotti
    - maxtico
