name: Build & Push Selenoprofiles docker

on:
  workflow_dispatch:      # manual trigger

permissions:
  contents: read

env:
  IMAGE_NAME: maxtico/selenoprofiles_container
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set VERSION from file
        id: ver
        run: |
          VERSION=$(python - <<'PY'
          import json, urllib.request
          print(json.load(urllib.request.urlopen("https://pypi.org/pypi/selenoprofiles4/json"))["info"]["version"])
          PY
          )
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Resolved version: $VERSION"

      - name: Build and push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          # Tag exactly as requested: v{version of selenxoprofiles}
          tags: ${{ env.IMAGE_NAME }}:v${{ steps.ver.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max